/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/documents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Upload
         * @description A raw PDF body, no multipart and no filename. Answers with every span judged.
         */
        post: operations["upload_api_documents_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/documents/{doc_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read
         * @description The document, in the reader's language. Worked out again only for a new `build`.
         */
        get: operations["read_api_documents__doc_id__get"];
        put?: never;
        post?: never;
        /**
         * Delete
         * @description The document and everything worked out from it, now rather than in an hour.
         */
        delete: operations["delete_api_documents__doc_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/documents/{doc_id}/pages/{n}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Page
         * @description Page `n` of the original, unrotated, `scale` pixels per point.
         *
         *     A page too big for that scale gets the largest that stays under the pixel
         *     limit. An old `build` still gets the image, but not to keep.
         */
        get: operations["page_api_documents__doc_id__pages__n__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/documents/{doc_id}/render": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Render
         * @description Each region drawn with the edits on its page, a fit per edit, and what was skipped.
         */
        post: operations["render_api_documents__doc_id__render_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/documents/{doc_id}/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Export
         * @description The edited document as a PDF: every page, or `pages` in that order.
         */
        post: operations["export_api_documents__doc_id__export_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/fonts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Fonts
         * @description Every face new text can be drawn in, by family, with each letter's width.
         *
         *     An old `build` still gets the list, but not to keep.
         */
        get: operations["fonts_api_fonts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Up and answering.
         */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * Box
         * @description A box on the page in points, top-left origin.
         */
        Box: {
            /** X0 */
            x0: number;
            /** Y0 */
            y0: number;
            /** X1 */
            x1: number;
            /** Y1 */
            y1: number;
        };
        /** @enum {string} */
        Category: "sans" | "serif" | "mono" | "handwriting";
        /**
         * Copy
         * @description The sentences the browser fills in as the user types, in the reader's language.
         */
        Copy: {
            /** Missing */
            missing: string;
            /** Too Long */
            too_long: string;
            /** Stand In */
            stand_in: string;
            /** Stand In Same Widths */
            stand_in_same_widths: string;
            /** Undo Redaction */
            undo_redaction: string;
            /** Options */
            options: {
                [key: string]: {
                    [key: string]: string;
                };
            };
        };
        /**
         * Document
         * @description The stored document, as the browser gets it, in the reader's language.
         */
        Document: {
            /** Build */
            build: string;
            /** Pages */
            pages: components["schemas"]["PageInfo"][];
            /** Spans */
            spans: components["schemas"]["SpanInfo"][];
            /** Fonts */
            fonts: components["schemas"]["FontInfo"][];
            /** Id */
            id: string;
            /** Expires At */
            expires_at: string;
            fit: components["schemas"]["FitRules"];
            copy: components["schemas"]["Copy"];
            /** Notices */
            notices: components["schemas"]["DocumentNoticeInfo"][];
        };
        /**
         * DocumentNoticeInfo
         * @description Something about the document that may not be what the user expected.
         *
         *     `type` is what the browser branches on; `detail` says it in the reader's
         *     words, and `code` and `params` are the same, unsaid.
         */
        DocumentNoticeInfo: {
            /** Code */
            code: string;
            /** Params */
            params: {
                [key: string]: components["schemas"]["Param"];
            };
            /** Type */
            type: string;
            /** Detail */
            detail: string;
        };
        /**
         * ExportBody
         * @description What export reads from the request body. No `pages` means every page.
         */
        ExportBody: {
            /** Edits */
            edits: (components["schemas"]["Replace"] | components["schemas"]["Redact"] | components["schemas"]["Insert"])[];
            /** Pages */
            pages?: number[] | null;
        };
        /**
         * FaceInfo
         * @description A face new text can be drawn in, and each letter it draws, by width.
         *
         *     `name` is what an insert's `font` asks for. Widths are in thousandths of the
         *     font size, the same the server measures with, so a preview matches the draw.
         */
        FaceInfo: {
            /** Name */
            name: string;
            style: components["schemas"]["Style"];
            /** Glyphs */
            glyphs: {
                [key: string]: number;
            };
        };
        /**
         * FamilyInfo
         * @description A family of faces we ship, and what kind of font it is.
         */
        FamilyInfo: {
            /** Family */
            family: string;
            category: components["schemas"]["Category"];
            /** License */
            license: string;
            /** Same Widths As */
            same_widths_as: string[];
            /** Faces */
            faces: components["schemas"]["FaceInfo"][];
        };
        /**
         * FitInfo
         * @description Whether a replacement fits, the ways out if not, and which one was drawn.
         */
        FitInfo: {
            /** Delta Pt */
            delta_pt: number;
            /** Missing */
            missing: string[];
            /** Left Out */
            left_out: string[];
            /** Options */
            options: components["schemas"]["Strategy"][];
            strategy: components["schemas"]["Strategy"];
            /** Message */
            message: string | null;
            /** Message Parts */
            message_parts: components["schemas"]["MessageInfo"][];
        };
        /**
         * FitRules
         * @description The thresholds the browser runs the fit check with, the server's own.
         */
        FitRules: {
            /** Tolerance Pt */
            tolerance_pt: number;
            /** Condense Limit */
            condense_limit: number;
            /** Shrink Floor */
            shrink_floor: number;
        };
        /**
         * FontInfo
         * @description A font the spans use, as the browser gets it: its facts, and why in the reader's words.
         *
         *     `why_code` and `why_params` are `why` unsaid, both empty when `why` is None.
         */
        FontInfo: {
            /** Name */
            name: string;
            /** Substitute */
            substitute: string | null;
            /** Why */
            why: string | null;
            /** Why Code */
            why_code: string | null;
            /** Why Params */
            why_params: {
                [key: string]: components["schemas"]["Param"];
            };
            /** Same Widths */
            same_widths: boolean;
            /** Glyphs */
            glyphs: {
                [key: string]: number;
            };
        };
        /**
         * FontList
         * @description Every face we ship, by family, under this build.
         */
        FontList: {
            /** Build */
            build: string;
            /** Families */
            families: components["schemas"]["FamilyInfo"][];
        };
        /**
         * ImageInfo
         * @description A drawn strip, its top `y` in points on the page, as a base64 PNG.
         */
        ImageInfo: {
            /** Page */
            page: number;
            /** Y */
            y: number;
            /** Image */
            image: string;
        };
        /**
         * Insert
         * @description Draw new text where the document has none: a signature, an annotation.
         *
         *     `font` names a face we ship (`core.fonts.FACES`, e.g. "Caveat Bold") or a
         *     font the document uses on this page. Anything else is drawn in a look-alike,
         *     and its fit says so: the fit always says what will really be drawn.
         */
        Insert: {
            /** Page */
            page: number;
            /** Origin */
            origin: [
                number,
                number
            ];
            /** Text */
            text: string;
            /** Size */
            size: number;
            /**
             * Font
             * @default Liberation Sans Regular
             */
            font?: string;
            /**
             * Color
             * @default [
             *       0,
             *       0,
             *       0
             *     ]
             */
            color?: [
                number,
                number,
                number
            ];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "insert";
        };
        /**
         * InsertFitInfo
         * @description An insert's fit, named by its place in the list the browser sent.
         */
        InsertFitInfo: {
            /** Delta Pt */
            delta_pt: number;
            /** Missing */
            missing: string[];
            /** Left Out */
            left_out: string[];
            /** Options */
            options: components["schemas"]["Strategy"][];
            strategy: components["schemas"]["Strategy"];
            /** Message */
            message: string | null;
            /** Message Parts */
            message_parts: components["schemas"]["MessageInfo"][];
            /** Edit */
            edit: number;
        };
        /**
         * MessageInfo
         * @description A Message as JSON: the sentence's key as `code`, and the facts that fill it.
         */
        MessageInfo: {
            /** Code */
            code: string;
            /** Params */
            params: {
                [key: string]: components["schemas"]["Param"];
            };
        };
        /**
         * NoticeInfo
         * @description An edit drawn other than asked, by its span or its place in the list, and why.
         *
         *     `detail` is why in the reader's words; `code` and `params` the same, unsaid.
         */
        NoticeInfo: {
            /** Code */
            code: string;
            /** Params */
            params: {
                [key: string]: components["schemas"]["Param"];
            };
            /** Span Id */
            span_id: string | null;
            /** Detail */
            detail: string;
            /** Edit */
            edit: number | null;
        };
        /**
         * PageInfo
         * @description A page unrotated, and the turn the browser gives it.
         */
        PageInfo: {
            /** Width */
            width: number;
            /** Height */
            height: number;
            /** Rotation */
            rotation: number;
        };
        Param: string | number | string[];
        /**
         * ProblemInfo
         * @description A Problem as the browser gets it: RFC 9457 Problem Details, plus its Message unsaid.
         *
         *     `detail` is shown verbatim; `code` is always `type`, and `params` fill it.
         */
        ProblemInfo: {
            /** Type */
            type: string;
            /** Status */
            status: number;
            /** Detail */
            detail: string;
            /** Code */
            code: string;
            /** Params */
            params: {
                [key: string]: components["schemas"]["Param"];
            };
            /** Debug */
            debug?: string;
        };
        /**
         * Redact
         * @description Remove a span's text and draw nothing in its place.
         *
         *     Mechanically the first half of a Replace. A covering rectangle would leave
         *     the text extractable underneath, which is how documents get leaked, so this
         *     deletes the text from the page itself and the result is checked by re-reading
         *     the output.
         */
        Redact: {
            /** Span Id */
            span_id: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "redact";
        };
        /**
         * Region
         * @description What to draw: a full-width strip of a page, from `y0` to `y1` in points, or all of it.
         */
        Region: {
            /** Page */
            page: number;
            /** Y0 */
            y0?: number | null;
            /** Y1 */
            y1?: number | null;
        };
        /**
         * Render
         * @description Render's reply, as the browser gets it: the strips, a fit per edit, and what it skipped.
         *
         *     `notices` are edits drawn other than asked, such as in a stand-in font.
         */
        Render: {
            /** Images */
            images: components["schemas"]["ImageInfo"][];
            /** Fits */
            fits: {
                [key: string]: components["schemas"]["FitInfo"];
            };
            /** Insert Fits */
            insert_fits: components["schemas"]["InsertFitInfo"][];
            /** Redactions */
            redactions: {
                [key: string]: string;
            }[];
            /** Skipped */
            skipped: components["schemas"]["SkippedInfo"][];
            /** Notices */
            notices: components["schemas"]["NoticeInfo"][];
            /** Build */
            build: string;
            /** Expires At */
            expires_at: string;
        };
        /**
         * RenderBody
         * @description What render reads from the request body.
         */
        RenderBody: {
            /** Edits */
            edits: (components["schemas"]["Replace"] | components["schemas"]["Redact"] | components["schemas"]["Insert"])[];
            /** Scale */
            scale: number;
            /** Regions */
            regions: components["schemas"]["Region"][];
        };
        /**
         * Replace
         * @description Swap a span's text: remove the old letters and draw the new ones in their place.
         */
        Replace: {
            /** Span Id */
            span_id: string;
            /** Text */
            text: string;
            /** @default as-is */
            strategy?: components["schemas"]["Strategy"];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "replace";
        };
        /**
         * SkippedInfo
         * @description An edit left out, by its place in the list the browser sent, and why.
         *
         *     `detail` is why in the reader's words; `code` and `params` the same, unsaid.
         */
        SkippedInfo: {
            /** Code */
            code: string;
            /** Params */
            params: {
                [key: string]: components["schemas"]["Param"];
            };
            /** Edit */
            edit: number;
            /** Type */
            type: string;
            /** Detail */
            detail: string;
        };
        /**
         * SpanInfo
         * @description One editable span and whether it keeps its own font.
         */
        SpanInfo: {
            /** Id */
            id: string;
            /** Page */
            page: number;
            /** Text */
            text: string;
            /** Font */
            font: string;
            /** Size */
            size: number;
            /** Color */
            color: number[];
            bbox: components["schemas"]["Box"];
            /** Origin */
            origin: number[];
            /** Fidelity */
            fidelity: string;
        };
        /** @enum {string} */
        Strategy: "as-is" | "shrink" | "condense";
        /** @enum {string} */
        Style: "regular" | "bold" | "italic" | "bold-italic";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    upload_api_documents_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Document"];
                };
            };
            /** @description Problem Details: what went wrong, in the reader's words */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemInfo"];
                    "application/json": components["schemas"]["ProblemInfo"];
                };
            };
        };
    };
    read_api_documents__doc_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                doc_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Document"];
                };
            };
            /** @description Problem Details: what went wrong, in the reader's words */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemInfo"];
                    "application/json": components["schemas"]["ProblemInfo"];
                };
            };
        };
    };
    delete_api_documents__doc_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                doc_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Problem Details: what went wrong, in the reader's words */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemInfo"];
                    "application/json": components["schemas"]["ProblemInfo"];
                };
            };
        };
    };
    page_api_documents__doc_id__pages__n__get: {
        parameters: {
            query: {
                scale: number;
                build: string;
            };
            header?: never;
            path: {
                n: number;
                doc_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "image/png": unknown;
                };
            };
            /** @description Problem Details: what went wrong, in the reader's words */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemInfo"];
                    "application/json": components["schemas"]["ProblemInfo"];
                };
            };
        };
    };
    render_api_documents__doc_id__render_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                doc_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RenderBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Render"];
                };
            };
            /** @description Problem Details: what went wrong, in the reader's words */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemInfo"];
                    "application/json": components["schemas"]["ProblemInfo"];
                };
            };
        };
    };
    export_api_documents__doc_id__export_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                doc_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExportBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/pdf": unknown;
                };
            };
            /** @description Problem Details: what went wrong, in the reader's words */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemInfo"];
                    "application/json": components["schemas"]["ProblemInfo"];
                };
            };
        };
    };
    fonts_api_fonts_get: {
        parameters: {
            query: {
                build: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FontList"];
                };
            };
            /** @description Problem Details: what went wrong, in the reader's words */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemInfo"];
                    "application/json": components["schemas"]["ProblemInfo"];
                };
            };
        };
    };
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
